"""
MCP Server factory and templates.

Provides scaffolding for creating custom MCP servers that integrate
with Claude Code's tool system.

Architecture:
    MCP servers extend Claude Code's capabilities by providing
    custom tools via the Model Context Protocol. This module
    generates server boilerplate so you can focus on tool logic.

Token implications:
    Each MCP tool adds ~100-300 tokens to the context window
    (tool name + description + parameter schema). Design tools
    with minimal but descriptive schemas.
"""

import json
from pathlib import Path
from textwrap import dedent


def create_mcp_server(
    name: str,
    output_dir: str | Path,
    tools: list[dict] | None = None,
    description: str = "",
) -> Path:
    """
    Generate a new MCP server project.

    Args:
        name: Server name (used in .mcp.json config)
        output_dir: Where to create the server directory
        tools: Optional list of tool definitions to scaffold
        description: Server description

    Returns:
        Path to the created server directory

    Example:
        ```python
        create_mcp_server(
            name="my-api",
            output_dir="./mcp-servers",
            tools=[
                {"name": "search", "description": "Search items", "params": {"query": "str"}},
                {"name": "create", "description": "Create item", "params": {"title": "str", "body": "str"}},
            ],
            description="My custom API integration"
        )
        ```
    """
    output_path = Path(output_dir) / name
    output_path.mkdir(parents=True, exist_ok=True)

    tools = tools or [
        {"name": "hello", "description": "A sample tool", "params": {"name": "str"}},
    ]

    _write_server_py(output_path, name, description, tools)
    _write_pyproject(output_path, name, description)
    _write_mcp_json_snippet(output_path, name)
    _write_test(output_path, name, tools)

    return output_path


def _write_server_py(path: Path, name: str, description: str, tools: list[dict]) -> None:
    tool_functions = []
    for tool in tools:
        params = tool.get("params", {})
        param_list = ", ".join(f"{k}: {v}" for k, v in params.items())
        param_docs = "\n".join(f"        {k}: The {k} parameter" for k in params)

        tool_functions.append(f'''
@mcp.tool()
def {tool["name"]}({param_list}) -> str:
    """{tool["description"]}

    Args:
{param_docs}
    """
    # TODO: Implement {tool["name"]} logic
    return f"{tool["name"]} called with: {", ".join(f"{{{k}}}" for k in params)}"
''')

    content = dedent(f'''
        """
        MCP Server: {name}
        {description}

        Generated by agent-lab. Customize the tool functions below.

        Usage:
            Add to .mcp.json:
            {{
                "mcpServers": {{
                    "{name}": {{
                        "command": "uv",
                        "args": ["run", "--directory", "{path.absolute()}", "python", "server.py"]
                    }}
                }}
            }}
        """

        from mcp.server.fastmcp import FastMCP

        mcp = FastMCP("{name}")

    ''').lstrip()

    content += "\n".join(tool_functions)

    content += dedent('''

        if __name__ == "__main__":
            mcp.run(transport="stdio")
    ''')

    (path / "server.py").write_text(content)


def _write_pyproject(path: Path, name: str, description: str) -> None:
    content = dedent(f'''
        [project]
        name = "{name}"
        version = "0.1.0"
        description = "{description}"
        requires-python = ">=3.11"
        dependencies = ["mcp"]

        [build-system]
        requires = ["hatchling"]
        build-backend = "hatchling.build"
    ''').lstrip()

    (path / "pyproject.toml").write_text(content)


def _write_mcp_json_snippet(path: Path, name: str) -> None:
    snippet = {
        "mcpServers": {
            name: {
                "command": "uv",
                "args": ["run", "--directory", str(path.absolute()), "python", "server.py"],
            }
        }
    }
    (path / "mcp-config-snippet.json").write_text(json.dumps(snippet, indent=2))


def _write_test(path: Path, name: str, tools: list[dict]) -> None:
    tool_calls = []
    for tool in tools:
        params = {k: f"test_{k}" for k in tool.get("params", {})}
        tool_calls.append(
            f'    {{"jsonrpc": "2.0", "id": {len(tool_calls) + 3}, "method": "tools/call", '
            f'"params": {{"name": "{tool["name"]}", "arguments": {json.dumps(params)}}}}}'
        )

    content = dedent(f'''
        """Integration test for {name} MCP server."""

        import json
        import subprocess
        from pathlib import Path


        def test_server():
            messages = [
                '{{"jsonrpc":"2.0","id":1,"method":"initialize","params":{{"protocolVersion":"2024-11-05","capabilities":{{}},"clientInfo":{{"name":"test","version":"1.0"}}}}}}',
                '{{"jsonrpc":"2.0","method":"notifications/initialized"}}',
                '{{"jsonrpc":"2.0","id":2,"method":"tools/list","params":{{}}}}',
        {chr(10).join(f"        '{call}'," for call in tool_calls)}
            ]

            stdin_data = "\\n".join(messages) + "\\n"

            result = subprocess.run(
                ["uv", "run", "python", "server.py"],
                input=stdin_data,
                capture_output=True,
                text=True,
                cwd=Path(__file__).parent,
                timeout=30,
            )

            responses = []
            for line in result.stdout.strip().split("\\n"):
                if line.strip():
                    responses.append(json.loads(line))

            print(f"Got {{len(responses)}} responses")
            for resp in responses:
                if "error" in resp:
                    print(f"  ERROR: {{resp['error']['message']}}")
                elif "result" in resp:
                    print(f"  [{{resp.get('id')}}] OK")

            assert len(responses) >= 2, f"Expected at least 2 responses, got {{len(responses)}}"
            print("\\nPASS")


        if __name__ == "__main__":
            test_server()
    ''').lstrip()

    (path / "test_server.py").write_text(content)
