"""
Hook generator for Claude Code lifecycle events.

Hooks are shell scripts that run OUTSIDE the LLM at specific lifecycle events.
They provide deterministic guardrails with zero token cost.

This module generates hook scripts and the corresponding settings.json entries.
"""

import stat
from pathlib import Path
from textwrap import dedent

HOOK_TEMPLATES = {
    "safety": {
        "event": "PreToolUse",
        "matcher": "Bash",
        "description": "Block dangerous shell commands",
        "script": dedent("""
            #!/bin/bash
            # Safety hook: blocks dangerous operations
            # Generated by agent-lab

            INPUT=$(cat)
            COMMAND=$(echo "$INPUT" | jq -r '.tool_input.command // empty')

            if [ -z "$COMMAND" ]; then
              exit 0
            fi

            # Block force pushes
            if echo "$COMMAND" | grep -qE "git\\s+push.*--force|git\\s+push.*-f\\b"; then
              echo "BLOCKED: Force push not allowed." >&2
              exit 2
            fi

            # Block destructive git operations
            if echo "$COMMAND" | grep -qE "git\\s+reset\\s+--hard"; then
              echo "BLOCKED: git reset --hard can lose work." >&2
              exit 2
            fi

            # Block rm -rf on source directories
            if echo "$COMMAND" | grep -qE "rm\\s+-rf\\s+(src|lib|app)/"; then
              echo "BLOCKED: Cannot recursively delete source directories." >&2
              exit 2
            fi

            exit 0
        """).strip(),
    },
    "secrets": {
        "event": "PreToolUse",
        "matcher": "Write",
        "description": "Prevent writing secrets to files",
        "script": dedent("""
            #!/bin/bash
            # Secrets protection hook
            # Generated by agent-lab

            INPUT=$(cat)
            FILE_PATH=$(echo "$INPUT" | jq -r '.tool_input.file_path // empty')
            CONTENT=$(echo "$INPUT" | jq -r '.tool_input.content // .tool_input.new_string // empty')

            # Block writes to sensitive files
            case "$FILE_PATH" in
              *.env|*.env.*|*credentials*|*secrets*|*.pem|*.key)
                echo "BLOCKED: Cannot write to sensitive file: $FILE_PATH" >&2
                exit 2
                ;;
            esac

            # Block hardcoded secrets
            if echo "$CONTENT" | grep -qiE "(api[_-]?key|secret|password|token)\\s*[=:]\\s*['\"][^'\"]{8,}"; then
              echo "BLOCKED: Content appears to contain hardcoded secrets." >&2
              exit 2
            fi

            exit 0
        """).strip(),
    },
    "audit": {
        "event": "PostToolUse",
        "matcher": None,
        "description": "Log all tool executions",
        "script": dedent("""
            #!/bin/bash
            # Audit logging hook (async — doesn't block execution)
            # Generated by agent-lab

            INPUT=$(cat)
            TOOL_NAME=$(echo "$INPUT" | jq -r '.tool_name // "unknown"')
            TIMESTAMP=$(date -Iseconds)
            LOG_DIR="${HOOK_LOG_DIR:-.claude/audit}"
            mkdir -p "$LOG_DIR"

            echo "{\\"ts\\":\\"$TIMESTAMP\\",\\"tool\\":\\"$TOOL_NAME\\"}" >> "$LOG_DIR/$(date +%Y-%m-%d).jsonl"

            exit 0
        """).strip(),
    },
    "notify": {
        "event": "Stop",
        "matcher": None,
        "description": "Notify when Claude finishes a turn",
        "script": dedent("""
            #!/bin/bash
            # Notification hook — terminal bell when done
            # Generated by agent-lab

            printf '\\a'
            exit 0
        """).strip(),
    },
}


def generate_hook(
    name: str,
    output_dir: str | Path,
    template: str = "safety",
    custom_script: str = "",
    event: str = "",
    matcher: str = "",
) -> tuple[Path, dict]:
    """
    Generate a hook script and its settings.json configuration.

    Args:
        name: Hook filename (without .sh)
        output_dir: Directory to write the script to
        template: One of 'safety', 'secrets', 'audit', 'notify'
        custom_script: Override template with custom script content
        event: Override the hook event (PreToolUse, PostToolUse, etc.)
        matcher: Override the tool matcher

    Returns:
        Tuple of (script_path, settings_entry) where settings_entry
        is the JSON object to add to .claude/settings.json hooks section.

    Example:
        ```python
        path, config = generate_hook(
            name="my-safety-hook",
            output_dir="./hooks",
            template="safety",
        )
        # config can be merged into .claude/settings.json
        ```
    """
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)

    if template in HOOK_TEMPLATES:
        tmpl = HOOK_TEMPLATES[template]
        script = custom_script or tmpl["script"]
        hook_event = event or tmpl["event"]
        hook_matcher = matcher or tmpl.get("matcher")
    else:
        script = custom_script or HOOK_TEMPLATES["safety"]["script"]
        hook_event = event or "PreToolUse"
        hook_matcher = matcher

    script_path = output_path / f"{name}.sh"
    script_path.write_text(script + "\n")
    script_path.chmod(script_path.stat().st_mode | stat.S_IEXEC)

    settings_entry = {
        "event": hook_event,
        "config": {
            "hooks": [
                {
                    "type": "command",
                    "command": f"cat | {script_path.absolute()}",
                }
            ]
        },
    }
    if hook_matcher:
        settings_entry["config"]["matcher"] = hook_matcher

    if template == "audit":
        settings_entry["config"]["hooks"][0]["async"] = True

    return script_path, settings_entry


def generate_settings_hooks(hooks: list[tuple[Path, dict]]) -> dict:
    """
    Combine multiple hook configs into a complete settings.json hooks section.

    Args:
        hooks: List of (path, config) tuples from generate_hook()

    Returns:
        Complete hooks section for .claude/settings.json
    """
    settings: dict = {}

    for _, config in hooks:
        event = config["event"]
        entry = config["config"]

        if event not in settings:
            settings[event] = []

        settings[event].append(entry)

    return {"hooks": settings}
